### PR TITLE
devstack and keystone changes the location of the config files

### PR DESCRIPTION
**Pull request by cp16net**
update the location of where we add the reddwarf service catalog

### CODE REVIEW

**Comment by rnirmal** [comment]
+1... FYI this could change when devstack updates stuff.

**Comment by cp16net** [comment]
That is true per this comment in devstack

```
# FIXME(dtroyer): etc/keystone.conf causes trouble if the config files
#                 are located anywhere else (say, /etc/keystone).
#                 LP 966670 fixes this in keystone, we fix it
#                 here until the bug fix is committed.
```

https://bugs.launchpad.net/keystone/+bug/966670

**Comment by ed-** [comment]
DO IT

which is to say +1

**Comment by hub-cap** [comment]
ug this is so annoying. +1

**Comment by hub-cap** [comment]
Im not sure i want to merge this. The fix is committed already in keystone trunk. Do we _need_ this anymore @cp16net ?

**Comment by cp16net** [comment]
i'm not sure... but i suspect we will still need this because keystone is being sent the /etc/keystone.conf file rather than the /opt/stack/keystone/etc/keystone.conf file.

I can test out the updates to devstack/keystone tomorrow.

**Comment by cp16net** [comment]
looks like this PR is still valid. I did update the paths that were actually wrong. and took out the unneeded quotes.

**Comment by hub-cap** [comment]
so it still _needs_ to be in /etc/? it doesnt use the keystone_dir/etc/ anymore?

**Comment by cp16net** [comment]
thats what devstack is starting up with.

**Pull request merged**
