### PR TITLE
Adds the xsd and wadl files from reddwarf classic.

### PR DESCRIPTION
**Pull request by ed-**
These are more or less unchanged, though I did change the field names of the rootDetails complextype, since I was just working on that.

### CODE REVIEW

**Comment by cp16net** [comment]
+1

**Comment by TimSimpsonR** [comment]
+1

**Comment by sacharya** [comment]
+1

**Comment by hub-cap** [comment]
lets wait on this until the pagination code is merged. Plz close @ed-

**Comment by ed-** [comment]
icing this one, too

**Pull request closed without merging**
