### PR TITLE
Fixed redstack to use updated glance client changes

### PR DESCRIPTION
**Pull request by sacharya**

### CODE REVIEW

**Comment by hub-cap** [comment]
Nice work @sacharya .That field stuff looks complicated. U might want to check what devstack is doing since they are needing to get that image id as well in their code.

**Comment by sacharya** [comment]
@hub-cap, I lifted that piece from devstack itself ;) Glance client prettified the output in tabular format.

**Comment by hub-cap** [comment]
Good man +1. Just making sure :) u da man.

**Comment by rnirmal** [comment]
+1

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

**Pull request merged**
