### PR TITLE
Removing hostname and ip from list instances

### PR DESCRIPTION
**Pull request by rnirmal**

### CODE REVIEW

**Comment by ed-** [comment]
+1 easy peasy

**Comment by hub-cap** [comment]
+1

**Comment by TimSimpsonR** [comment]
+1
We might want to change the tests to check that these things _aren't_ here, what with all the attributes that keep sneaking into other calls.

**Comment by cp16net** [comment]
+1 and i agree with @TimSimpsonR

**Comment by imsplitbit** [comment]
+1

**Comment by rnirmal** [comment]
yeah we'll need to do that.

**Pull request merged**
