### PR TITLE
put the order of the cmds correctly in the list

### PR DESCRIPTION
**Pull request by cp16net**
get some of the instance tests working around create

### CODE REVIEW

**Comment by hub-cap** [comment]
+1. didnt realize it requires init, but ya, cuz of glance/keystone/auth/et.al, it def does :D

**Comment by hub-cap** [comment]
on second thought -1. the print_usage() command should mirror the order of those commands more than the actual case loop itself. Can u update this so it also properly reflects.

**Comment by cp16net** [comment]
How about that?

**Comment by ed-** [comment]
Since I use redstack's help message to remember just where I was in the process, I appreciate the grouping and ordering.

**Comment by TimSimpsonR** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Pull request merged**
