### PR TITLE
update int. rel. notes for v1.0.12 9/17; update int. release notes, Mgmt...

### PR DESCRIPTION
**Pull request by masthalter**
... Devguide, Mgmt wadl for v1.0.13 10/2

### CODE REVIEW

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

This is a new +1 following the addition of the getaccounts documentation in the recent update.

**Comment by TimSimpsonR** [comment]
+1

**Comment by jcru** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Pull request merged**
