### PR TITLE
Adds fake-sql to our command list. Nothing fancy.

### PR DESCRIPTION
**Pull request by ed-**
Should be straightforward.

### CODE REVIEW

**Comment by rnirmal** [comment]
+1 But I'm still opposed to adding a whole barrage of commands to redstack. But hey it's a developer tool so no issues.

**Comment by TimSimpsonR** [comment]
+1
I am pro-having a thousand commands in Redstack. Maybe we could do something to make the help screen only show so many, and have some other option to show the rest of them.

**Comment by ed-** [comment]
I was considering rerouting rd-sql if FAKE_MODE=True but I figured this would come in handy on its own

**Comment by cp16net** [comment]
i like the usefulness of all the cmds that redstack brings along. I kind of like the idea that tim said and maybe we could make it only print the default helpful setup type of cmd normally and add a `--verbose` or `--help` maybe for all the commands.

**Comment by cp16net** [comment]
+1 on this add

**Pull request merged**
