### PR TITLE
Adding the ability to put known bugs into the RDLI test config.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Made minor fix to config.py to make errors in the config file easier
  to diagnose.

### CODE REVIEW

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by hub-cap** [comment]
-100 i hate u. now and forever. :P

**Comment by jcru** [comment]
+1

**Comment by TimSimpsonR** [comment]
Merging in spite of Baz's spitefulness. ◕╭╮◕

**Pull request merged**
